name: Rodar script todos os dias

on:
  schedule:
    - cron: '0 23 * * *'  # Roda às 23h UTC = 20h no Brasil (horário padrão)
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Rodar script com variáveis de ambiente
      run: |
        python 03_GITHUB_UNIFICADO_COMPLETO.py
      env:
        EMAIL_SENHA_APP: ${{ secrets.EMAIL_SENHA_APP }}
        EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
        EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
